# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('CREATED', 'Order created'), ('SENT TO KITCHEN', 'Order sent to kitchen'), ('STARTED', 'Order started'), ('READY', 'Order ready to be served'), ('SERVED', 'Order served'), ('COMPLETED', 'Order completed')], default='CREATED', max_length=15),
        ),
    ]
