# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161028155252 on 2016-11-12 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Nutrition', models.CharField(max_length=200)),
                ('Price', models.IntegerField(default=170)),
            ],
        ),
    ]
